# Change these first
owner: stupldstuff # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: rudi
    url: $ENDPOINT_INNERRUDI_URL
  - name: rudi vercel
    url: $ENDPOINT_RUDI_VERCEL_URL
  - name: wummy (für freund)
    url: https://wummy.one/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: ocean
  introTitle: "**Upptime**"
  introMessage: yay uptime & downtime yay
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
